### ISSUE TITLE
Performance: getReachableShapes

### ISSUE THREAD

**Issue by gunnarmein** [EastsidePreparatorySchool/FusorComputationalModeling#30]
getReachableShapes is called in every iteration of the for-loop in balanceCharges. Since all negative parts are connected to only one HV source, and all positive parts are connected to ground, I state that there are exactly two possible lists of reachableShapes, one for positive and one for negative electrons. These should be precomputed and simply looked up, not compiled from scratch every time.  

Alternatively, the method could store the result lists in 2 static or member cache variables and return that value if it is not null.

**Comment by guberti** [comment]
Just built a fix to this. We're seeing incredible performance increases! Previously, for my Bent Sphere JSON file (the realistic one), it took 85.2493 seconds to perform 20 shake-up operations on 2000 total points. Now, it takes just **29.4334** seconds - approximately a 3x increase!
