### ISSUE TITLE
performance: getSurfaceArea

### ISSUE THREAD

**Issue by gunnarmein** [EastsidePreparatorySchool/FusorComputationalModeling#31]
Every time we choose a random point, we compute the surface area of parts over and over again. That value needs to be cached. Here is one easy way:

- In GridComponent, make a new method getSurfaceAreaCached. In it, set a member variable with the area the first time you compute it. Call getSurfaceArea to compute it. Return the cached value every time thereafter. Change the use of this function in PointDistributor to use the cached version of the method instead.

**Comment by guberti** [comment]
Issues #30 to #33 look pretty simple, will write quick fixes for them tonight.

**Comment by gunnarmein** [comment]
I would use caution with #33. A mistake here would influence the math in an undetectable way.

**Comment by gunnarmein** [comment]
Didn't mean to close this.

**Comment by guberti** [comment]
Just ran a benchmark test to determine how shakeUpPoints runs right now. For my Bent Sphere JSON file (the realistic one), **it takes 85.2493 seconds to perform 20 shake-up operations on 2000 total points**. Note that the Bent Sphere JSON object includes a complex STL file.

**Comment by guberti** [comment]
After fixing #30, the operation described above takes 29.4334 seconds.

**Comment by guberti** [comment]
Just built a fix for this. No meaningful change in performance visible.

**Comment by gunnarmein** [comment]
Your stl file is not a great case for this fix. This one only matters when surface area involves more complex calculations, like the torus segment. Triangles are too simple. But, we may never have enough complex shapes for this to matter.
